INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Lácteos', 'Leche y derivados lácteos');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Verduras', 'Vegetales frescos');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Cafés', 'Cafe molido, cápsulas, etc.');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Navidad', 'Productos navideños diversos (decoración, adornos, etc.)');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Electrónica', 'Ordenadores, periféricos, etc.');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Bebidas', 'Refrescos con/sin gas');
INSERT INTO `poo2022`.`Categories` (`CategoryName`, `Description`) VALUES ('Panadería', 'Panes, bollos, etc.');
INSERT INTO `poo2022`.`Categories` (`CategoryName`) VALUES ('Bombillas');
INSERT INTO `poo2022`.`Categories` (`CategoryName`) VALUES ('Papelería');
INSERT INTO `poo2022`.`Categories` (`CategoryName`) VALUES ('Juguetes');